export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_COLOR = "SET_COLOR";



export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SETTED_TOTAL_USERS = "SETTED_TOTAL_USERS";






export const BACKGAMMON_GOT_GAMEID = "BACKGAMMON_GOT_GAMEID";
